# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none

# Setup
title:               "thathungrymind"
tagline:             "my brain food"
description:         "thathungrymind | my brain food"
url:                 #"http://lenpaul.github.io"
baseurl:             #"/hungry-minds"
gems:                [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              "Paul Le"
  url:               "https://twitter.com/paululele"
  email:             "l.nguyen.paul@gmail.com"
  twitter:           "paululele"

# Custom vars
share-url:           "https://www.thathungrymind.com"
